# Generated by Django 5.2.7 on 2025-11-13 22:03

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athena', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_jornalista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('data_atualizada', models.DateTimeField(auto_now=True)),
                ('regiao', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='NoticiaComTag', to='athena.tag')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jornalista.perfil')),
            ],
            options={
                'ordering': ['data_atualizada'],
            },
        ),
    ]
