# Generated by Django 5.2.7 on 2025-11-06 20:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0001_initial'),
        ('athena', '0002_delete_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('data_atualizada', models.DateTimeField(auto_now=True)),
                ('jornalista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jornalista.perfil')),
                ('tags', models.ManyToManyField(related_name='NoticiaComTag', to='athena.tag')),
            ],
            options={
                'ordering': ['data_atualizada'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
