# Generated by Django 5.2.7 on 2025-11-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0002_noticia_delete_post'),
        ('athena', '0002_delete_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='NoticiaComTag', to='athena.tag'),
        ),
    ]
