# Generated by Django 5.2.7 on 2025-12-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0002_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumo',
            field=models.CharField(blank=True, help_text='Resumo da notícia que aparecerá na home e pesquisas', max_length=200, null=True),
        ),
    ]
