# Generated by Django 5.2.7 on 2025-11-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0002_alter_perfil_user_noticia_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='jornalista',
            new_name='autor',
        ),
    ]
