# Generated by Django 5.2.7 on 2025-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0004_noticia_latitude_noticia_longitude_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='Regiao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
