# Generated by Django 5.2.7 on 2025-11-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0005_noticia_regiao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='Regiao',
            new_name='regiao',
        ),
    ]
