# Generated by Django 5.2.7 on 2025-11-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0002_alter_perfil_user_noticia_delete_post'),
        ('athena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='relevantes',
            field=models.ManyToManyField(related_name='PerfilComNoticia', to='Jornalista.noticia'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tags',
            field=models.ManyToManyField(related_name='perfilComTag', to='athena.tag'),
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
