# Generated by Django 5.2.7 on 2025-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0001_initial'),
        ('athena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='relevantes',
            field=models.ManyToManyField(related_name='PerfilComNoticia', to='Jornalista.noticia'),
        ),
    ]
