# Generated by Django 5.2.7 on 2025-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0002_noticia_imagem'),
        ('athena', '0002_perfil_relevantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='relevantes',
            field=models.ManyToManyField(blank=True, related_name='PerfilComNoticia', to='Jornalista.noticia'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='perfilComTag', to='athena.tag'),
        ),
    ]
