# Generated by Django 5.2.7 on 2025-11-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0003_alter_noticia_tags'),
        ('athena', '0002_delete_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='relevantes',
            field=models.ManyToManyField(related_name='PerfilComNoticia', to='Jornalista.noticia'),
        ),
    ]
