# Generated by Django 5.2.7 on 2025-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0003_perfil_relevantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
