# Generated by Django 5.2.7 on 2025-12-04 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jornalista', '0003_noticia_resumo'),
        ('athena', '0003_alter_perfil_relevantes_alter_perfil_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('noticia', 'Feedback sobre Notícia'), ('site', 'Feedback sobre o Site')], default='noticia', max_length=10, verbose_name='Tipo de Feedback')),
                ('avaliacao', models.IntegerField(choices=[(1, '1 - Muito Ruim'), (2, '2 - Ruim'), (3, '3 - Razoável'), (4, '4 - Bom'), (5, '5 - Muito Bom'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10 - Excelente')], verbose_name='Avaliação (1-10)')),
                ('comentario', models.TextField(help_text='Deixe um comentário sobre o feedback (máximo 500 caracteres)', max_length=500, verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Jornalista.noticia', verbose_name='Notícia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meus_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
